chg: dev: adding a new macro for stress testing in macros.yaml
this is an effort to verify the reliability of tests when
a new tests are checked in as part of the review

Change-Id: Ib1a7b3d37b935f4b899fc6494ffb14f2a4ff212a
Signed-off-by: Akshar Ranka <akshar.ranka@hpe.com>

diff --git a/jenkins/jobs/macros.yaml b/jenkins/jobs/macros.yaml
--- a/jenkins/jobs/macros.yaml
+++ b/jenkins/jobs/macros.yaml
@@ -772,6 +772,97 @@
              echo "Skipping cttest"
            fi
 
+- builder:
+    name: module-stress-test
+    builders:
+      - shell: |
+           #!/bin/bash -x
+           set +e
+           MOD_FRAMEWORK="^ops-tests/.*\.py$"
+           PATTERN="^(.*?\/)?tests\/(.*?\/)?test_.*?.py$"
+           TEST_FAILURE=0
+           EXIT_FLAG=0
+           TEST_TYPE=""
+
+           if git ls-remote https://git.openswitch.net/openswitch/ops | grep -swq "$ZUUL_BRANCH" ; then
+             OPS_BRANCH=$ZUUL_BRANCH
+           else
+             OPS_BRANCH=master
+           fi
+           rm -rf build/test/*/test-results.xml
+           cd src/{module}
+           arr_files=($(git diff-tree --no-commit-id --name-only -r $ZUUL_COMMIT))
+           cat extension.txt
+           if [ {platform} == "genericx86-64" ]
+           then
+             cd $WORKSPACE
+             touch .devenv
+             make testenv_init
+             export TOPOLOGY_TEST_IMAGE=$(echo $JOB_NAME-$BUILD_NUMBER  | tr '[A-Z]' '[a-z]')
+
+             SECOND_RUN_COMMAND=testenv_run
+             for tst in "${arr_files[@]}"
+             do
+               echo $tst
+               TEST_FAILURE=0
+
+               if [ ! -f src/{module}/$tst ]
+               then
+                 echo "skipping deleted file"
+                 continue
+               fi
+
+               if [[ $tst =~ $MOD_FRAMEWORK ]];
+               then
+                 TEST_TYPE="component"
+               elif [[ $tst =~ $PATTERN ]];
+               then
+                 TEST_TYPE="legacy"
+               else
+                 continue
+               fi
+
+               make $SECOND_RUN_COMMAND $TEST_TYPE {module} TESTENV_STRESS=yes TESTENV_ITERATIONS=5 TESTENV_EXTRA_PARAMETERS="-k $tst"
+               SECOND_RUN_COMMAND=testenv_rerun
+               if [ $? != 0 ]
+               then
+                 TEST_FAILURE=1
+               fi
+               if [ $TEST_FAILURE != 0 ]
+               then
+                 EXIT_FLAG=1
+                 make devenv_ct_clean
+                 echo $tst "failed"
+               fi
+             done
+
+             if [ $EXIT_FLAG == 1 ]
+             then
+               docker rmi -f $VSI_IMAGE_NAME
+               exit 3
+             else
+
+             set -e
+             # If we have modular component tests, we run them
+             if [ -d src/{module}/ops-tests/component ] ; then
+               make $SECOND_RUN_COMMAND component {module}
+               SECOND_RUN_COMMAND=testenv_rerun
+             fi
+             # If this module still has legacy component test, we run them too, otherwise only the legacy feature
+             if [ -d src/{module}/tests ] ; then
+                TESTS_TO_RUN="{module} ops"
+             else
+                TESTS_TO_RUN="ops"
+             fi
+             # build the fs, export into docker, and download the repos and run the tests
+             make $SECOND_RUN_COMMAND legacy $TESTS_TO_RUN
+             test -e .sandbox_uuid && make devenv_ct_clean
+             /usr/local/jenkins/slave_scripts/docker_clean_instances_and_image.sh $TOPOLOGY_TEST_IMAGE
+             sudo chown jenkins.jenkins build/test/*/test-results.xml
+           else
+             echo "Skipping tests because it is not a genericx86-64 platform"
+           fi
+
 #- builder:
 #    name: gulp-dist
 #    builders:
