Adding  new checks for on demand CIT
Change-Id: Ia9665ea01da10799ef735e95ede18cf660713d08

diff --git a/jenkins/jobs/macros.yaml b/jenkins/jobs/macros.yaml
--- a/jenkins/jobs/macros.yaml
+++ b/jenkins/jobs/macros.yaml
@@ -286,10 +286,18 @@
            set +x
            # Identify the branch to use for the build system
            if git ls-remote https://git.openswitch.net/openswitch/ops-build | grep -swq "$Feature_BranchName" ; then
+              echo "Checking if $Feature_BranchName exists in ops-build repository"
               OPS_BUILD_BRANCH=$Feature_BranchName
            else
-              OPS_BUILD_BRANCH=master
+              echo "****************************************************************************************"
+              echo "WARNING: cannot find $Feature_BranchName in ops-build"
+              echo "Please provide a Feature Branch name that exists and try again.
+              echo "****************************************************************************************"
+              echo "Here are the list of Feature Branches available"
+              git ls-remote https://git.openswitch.net/openswitch/ops-build | grep -i "Feature"
+              exit 1
            fi
+           if [ $? -eq 0 ] ; then
            echo "===================  Building ops-build on $OPS_BUILD_BRANCH =================== "
            rm -fr .[^.]* *
            git clone -b $OPS_BUILD_BRANCH https://git.openswitch.net/openswitch/ops-build .
@@ -297,20 +305,24 @@
            export SSTATE_DIR=/mnt/jenkins/workspace/sstate-cache
            mkdir -p /mnt/jenkins/workspace/sstate-cache
            # Check if we need to configure
-           if [ ! -f .platform ] ; then
-            make configure genericx86-64
-           fi
+              if [ ! -f .platform ] ; then
+                make configure genericx86-64
+              fi
            Repositories_List=`echo $Repositories_List | sed -e 's#,# #'`
            # Chect out all repo
            rm -rf src/*
            for i in $Repositories_List
             do
-                if git ls-remote https://git.openswitch.net/openswitch/ops-build | grep -swq "$Feature_BranchName" ; then
+                if git ls-remote https://git.openswitch.net/openswitch/$i | grep -swq "$Feature_BranchName" ; then
+                    echo "Checking if $Feature_BranchName exists in $i repository"
                     OPS_BUILD_BRANCH=$Feature_BranchName
                 else
+                    echo "****************************************************************************************"
+                    echo "WARNING: cannot find $Feature_BranchName in $i, so using master branch instead. "
+                    echo "****************************************************************************************"
                     OPS_BUILD_BRANCH=master
                 fi
-           git clone -b $OPS_BUILD_BRANCH http://git.openswitch.net/openswitch/$i src/$i > /dev/null 2>&1
+              git clone -b $OPS_BUILD_BRANCH http://git.openswitch.net/openswitch/$i src/$i > /dev/null 2>&1
            done
            set -e
            # clean up .xml
@@ -328,16 +340,26 @@
            export VSI_IMAGE_NAME=$y
            echo $VSI_IMAGE_NAME > .image_name
            make export_docker_image $VSI_IMAGE_NAME
-           #Repositories_List=`echo $REPOS | sed -e 's#,# #'`
            Repositories_List=`echo $Repositories_List | sed -e 's#,# #'`
            for i in $Repositories_List
            do
-            echo "*************************************** Testing $i repo ***************************************"
-            make devenv_ct_test PY_TEST_ARGS="src/$i/tests --junit-xml=build/module-test-results.xml"  || (make devenv_ct_clean; docker rmi -f $VSI_IMAGE_NAME; exit 1)
+            if [ "$i" == "ops-build" ]; then
+            echo"No need to provide ops-build in List of repositories, skipping this step"
+            continue
+            else
+              if [ -d "$WORKSPACE/src/$i/tests" ]; then
+                 echo "*************************************** Testing $i repo ***************************************"
+                 make devenv_ct_test PY_TEST_ARGS="src/$i/tests --junit-xml=build/module-test-results.xml"  || (make devenv_ct_clean; docker rmi -f $VSI_IMAGE_NAME; exit 1)
+              else
+                 echo "Tests folder does not exist in $i repo, skip running tests"
+                 continue
+              fi
+            fi
            done
            test -e .sandbox_uuid && make devenv_ct_clean
            docker images | grep $VSI_IMAGE_NAME && docker rmi -f $VSI_IMAGE_NAME
            sudo chown jenkins.jenkins build/*-test-results.xml
+           fi
 
 - builder:
     name: fttest-for-image
