Adding  fixes to commit validation logic
Change-Id: I02c3863372aa413154a5bb5d1fe3300be7c794e5

diff --git a/jenkins/jobs/macros.yaml b/jenkins/jobs/macros.yaml
--- a/jenkins/jobs/macros.yaml
+++ b/jenkins/jobs/macros.yaml
@@ -89,6 +89,13 @@
           commit_msg=`git log --pretty=format:%s%b -n 1`
           # To validate if a commit message has Taiga ID in format TG-XXX
           id_state=`echo $commit_msg | grep -i "TG-[0-9].*" | wc -l`
+          if [ -z "$id_state" ]; then
+            echo "Unable to determine if a valid Taiga ID is provided"
+            echo "commit message received is $commit_msg"
+            echo "If you believe you have provided a Taiga ID in your commit message, this means that the script is not able to parse it"
+            echo "Please make sure there is a space in front of TG-XXX in your commit message, please amend your commit message and upload for review again"
+            exit 1
+          fi
           if [ $id_state -ne 0 ]; then
                 echo "Taiga ID exists in commit message"
                 #parse the Taiga IDs in commit message
@@ -113,6 +120,11 @@
                     echo "Contact Barbara Crosser(barbara.crosser@hpe.com) or Chia-Lien Huang(chia-lien.huang@hpe.com) to get this defect approved"
                     exit 1
                 fi
+            else
+                echo "Please provide appropriate Taiga id that is in list of approved fixes for release branch in your commit message"
+                echo "$taiga_ids are not in Approved list of defects"
+                echo "Failing the Build"
+                exit 1
             fi
            else
             echo "Commit Message Validation is Skipped since it is not a release branch"
