Adding  commit message validation to all check jobs
Change-Id: I11c0d2a9c743419fcdec6c8ed995d8e05d9d766a

diff --git a/jenkins/jobs/macros.yaml b/jenkins/jobs/macros.yaml
--- a/jenkins/jobs/macros.yaml
+++ b/jenkins/jobs/macros.yaml
@@ -75,7 +75,60 @@
               echo ""
           fi
           make
-
+- builder:
+    name: commit-message-validation-ops
+    builders:
+      - shell: |
+          #!/bin/bash -x
+          set +x
+          echo "ZUUL_BRANCH $ZUUL_BRANCH"
+          if [ "$ZUUL_BRANCH" = "rel/dill" ] ; then
+          cd $WORKSPACE
+          echo "Validating git commit message if it contains a valid Taiga ID in the format of TG-XXX, for example, TG-123 and that it is in list of allowed fixes for rel/dill branch"
+          # Obtain only git commit message from HEAD, can be multi-line with white spaces
+          commit_msg=`git log --pretty=format:%s%b -n 1`
+          # To validate if a commit message has Taiga ID in format TG-XXX
+          id_state=`echo $commit_msg | grep -i "TG-[0-9].*" | wc -l`
+          if [ -z "$id_state" ]; then
+            echo "Unable to determine if a valid Taiga ID is provided"
+            echo "commit message received is $commit_msg"
+            echo "If you believe you have provided a Taiga ID in your commit message, this means that the script is not able to parse it"
+            echo "Please make sure there is a space in front of TG-XXX in your commit message, please amend your commit message and upload for review again"
+            exit 1
+          fi
+          if [ $id_state -ne 0 ]; then
+                echo "Taiga ID exists in commit message"
+                #parse the Taiga IDs in commit message
+                taiga_ids=`echo $commit_msg | tr -s " " | tr " " "\n" | grep ^TG | sed "s/TG-//g" | tr "\n" "," | sed 's/,$//'`
+                git clone https://git.openswitch.net/infra/commit-validation
+                tickets_list=`echo $taiga_ids | sed -e 's#,# #g'`
+                for i in $tickets_list; do
+                    defect_exists=`cat commit-validation/TaigaApprovedDefects.csv | cut -d',' -f1 | grep -w $i | wc -l`
+                    if [ $defect_exists -eq 1 ]; then
+                        echo "Taiga Defect TG-$i is in list of allowed defects for release branch"
+                        echo "Validation successful"
+                        exit 0
+                        defect_found=1
+                    else
+                        defect_found=0
+                    fi
+                done
+                if [ $defect_found -eq 0 ]; then
+                    echo "Commit Message Validation failed"
+                    echo "A Taiga ID should be in a separate line by itself. If the message has multiple Taiga ID, each one needs to be in a separate line"
+                    echo "The Taiga ID(s) provided in commit message is not in the list of allowed defects for the release branch"
+                    echo "Contact Barbara Crosser(barbara.crosser@hpe.com) or Chia-Lien Huang(chia-lien.huang@hpe.com) to get this defect approved"
+                    exit 1
+                fi
+            else
+                echo "Please provide appropriate Taiga id that is in list of approved fixes for release branch in your commit message"
+                echo "$taiga_ids are not in Approved list of defects"
+                echo "Failing the Build"
+                exit 1
+            fi
+           else
+            echo "Commit Message Validation is Skipped since it is not a release branch"
+           fi
 - builder:
     name: commit-message-validation
     builders:
