Adding   a new job for on-demand CIT
Change-Id: Ic92edeb65d70bdc417bc8d7cf68d3c2358a42bbe

diff --git a/jenkins/jobs/macros.yaml b/jenkins/jobs/macros.yaml
--- a/jenkins/jobs/macros.yaml
+++ b/jenkins/jobs/macros.yaml
@@ -279,6 +279,66 @@
            fi
 
 - builder:
+    name: ops-selfservice-cit-ondemand
+    builders:
+      - shell: |
+           #!/bin/bash -x
+           set +x
+           # Identify the branch to use for the build system
+           if git ls-remote https://git.openswitch.net/openswitch/ops-build | grep -swq "$Feature_BranchName" ; then
+              OPS_BUILD_BRANCH=$Feature_BranchName
+           else
+              OPS_BUILD_BRANCH=master
+           fi
+           echo "===================  Building ops-build on $OPS_BUILD_BRANCH =================== "
+           rm -fr .[^.]* *
+           git clone -b $OPS_BUILD_BRANCH https://git.openswitch.net/openswitch/ops-build .
+           # Setup the shared state local cache
+           export SSTATE_DIR=/mnt/jenkins/workspace/sstate-cache
+           mkdir -p /mnt/jenkins/workspace/sstate-cache
+           # Check if we need to configure
+           if [ ! -f .platform ] ; then
+            make configure genericx86-64
+           fi
+           Repositories_List=`echo $Repositories_List | sed -e 's#,# #'`
+           # Chect out all repo
+           rm -rf src/*
+           for i in $Repositories_List
+            do
+                if git ls-remote https://git.openswitch.net/openswitch/ops-build | grep -swq "$Feature_BranchName" ; then
+                    OPS_BUILD_BRANCH=$Feature_BranchName
+                else
+                    OPS_BUILD_BRANCH=master
+                fi
+           git clone -b $OPS_BUILD_BRANCH http://git.openswitch.net/openswitch/$i src/$i > /dev/null 2>&1
+           done
+           set -e
+           # clean up .xml
+           rm -rf build/*-test-results.xml
+           # set devenv
+           set +e
+           make devenv_init || true
+           set -e
+           # building image
+           cd $WORKSPACE
+           make fs
+           # init ct
+           make devenv_ct_init
+           y=`echo $JOB_NAME-$BUILD_NUMBER  | tr '[A-Z]' '[a-z]'`
+           export VSI_IMAGE_NAME=$y
+           echo $VSI_IMAGE_NAME > .image_name
+           make export_docker_image $VSI_IMAGE_NAME
+           Repositories_List=`echo $REPOS | sed -e 's#,# #'`
+           for i in $Repositories_List
+           do
+            echo "*************************************** Testing $i repo ***************************************"
+            make devenv_ct_test PY_TEST_ARGS="src/$i/tests --junit-xml=build/module-test-results.xml"  || (make devenv_ct_clean; docker rmi -f $VSI_IMAGE_NAME; exit 1)
+           done
+           test -e .sandbox_uuid && make devenv_ct_clean
+           docker images | grep $VSI_IMAGE_NAME && docker rmi -f $VSI_IMAGE_NAME
+           sudo chown jenkins.jenkins build/*-test-results.xml
+           
+- builder:
     name: fttest-for-image
     builders:
       - shell: |
