Try to restart docker daemon
Tags: chg,dev
* check-docker-state macro checks if docker daemon
  is running and throws an error. Adding a command to
  try and restart docker daemon as part of this macro.

Change-Id: Icbbb3bc836b2f63d30346088b62b7ff67d440b00
Signed-off-by: Vasanth Viswanathan <vasanth.viswanathan@hpe.com>

diff --git a/jenkins/jobs/macros.yaml b/jenkins/jobs/macros.yaml
--- a/jenkins/jobs/macros.yaml
+++ b/jenkins/jobs/macros.yaml
@@ -484,8 +484,14 @@
            docker version
            if [ $? != 0 ]
            then
-             echo "Docker command failed. Check if docker daemon is running."
-             exit 1
+             echo "Docker daemon is not running. Try to restart."
+             sudo service docker restart
+             docker version
+             if [ $? != 0 ]
+             then
+                 echo "Docker daemon failed to restart. Aborting the build."
+                 exit 1
+             fi
            else
              docker ps -a
              docker images
