adding jenkins job for stage website
Change-Id: Idba28ed16d1cba72fd6474fcf014be5a6baa5b0a

diff --git a/jenkins/jobs/website.yaml b/jenkins/jobs/website.yaml
--- a/jenkins/jobs/website.yaml
+++ b/jenkins/jobs/website.yaml
@@ -70,3 +70,54 @@
                 source: 'www/**'
                 keep-hierarchy: true
                 copy-after-failure: false
+
+- job:
+    name: 'website-stage-hourly'
+    node: openswitch
+
+    wrappers:
+        - build-timeout:
+            timeout: 60
+        - timestamps
+        - ansicolor
+
+    triggers:
+        - timed: '@hourly'
+
+    builders:
+        - revoke-sudo
+        - shell: |
+            #!/bin/bash -x
+            set -e
+
+            if [[ ! -e .git ]]; then
+              # Remove any content, otherwise the clone will fail
+              rm -Rf *
+              git clone https://git.openswitch.net/openswitch/ops-build .
+            else
+              git pull
+            fi
+            mkdir -p /mnt/jenkins/workspace/sstate-cache
+            export SSTATE_DIR=/mnt/jenkins/workspace/sstate-cache
+            if [ ! -f .platform ] ; then
+                make configure genericx86-64
+            fi
+            touch .devenv # hack to enable devenv
+            if [ ! -d src/ops-website ] ; then
+                make devenv_add ops-website
+                make ops-website-setup
+            fi
+            make ops-website-build
+            make ops-website-update
+            make ops-website-dist
+            rm -Rf egats
+            cp -R src/ops-website/dist egats
+
+    publishers:
+        - scp:
+            site: static.openswitch.net
+            files:
+              - target: ''
+                source: 'egats/**'
+                keep-hierarchy: true
+                copy-after-failure: false
